project_name: portman

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: portman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: portman
    tap:
      owner: ritiksuman007
      name: homebrew-tap
    homepage: "https://github.com/ritiksuman07/portman"
    description: "Local port and process manager for developers"
    license: "MIT"
